### ISSUE TITLE
`ReadOnlyMemoryError()` on `julia v0.6`

### ISSUE THREAD

**Issue by raminammour** [JuliaParallel/DistributedArrays.jl#150]
Hello, 

I have been seeing this error on `0.6` (I am on master), working in Jupyter. It happens inconsistently:

```
bbb=drand(101,11)
bbb[1,1]

ReadOnlyMemoryError()

Stacktrace:
 [1] getindex_tuple(::DistributedArrays.DArray{Float64,2,Array{Float64,2}}, ::Tuple{Int64,Int64}) at /data/gpfs/Users/j0280401/JULIA/v0.6/DistributedArrays/src/darray.jl:543
 [2] getindex(::DistributedArrays.DArray{Float64,2,Array{Float64,2}}, ::Int64, ::Int64) at /data/gpfs/Users/j0280401/JULIA/v0.6/DistributedArrays/src/darray.jl:551
```

**Comment by andreasnoack** [comment]
Hm. I haven't seen this one before. Could you provide more information about your setup/machine?

**Comment by raminammour** [comment]
```julia
versioninfo()

Julia Version 0.6.0
Commit 9036443 (2017-06-19 13:05 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Xeon(R) CPU E5-4640 0 @ 2.40GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Sandybridge)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.9.1 (ORCJIT, sandybridge)
```
The weird thing is that it does not always happen.

**Comment by andreasnoack** [comment]
I could look like your packages are on a shared file system. Is that correct?

**Comment by raminammour** [comment]
Yes, the packages are on a shared file system.

**Comment by andreasnoack** [comment]
Is the code snippet in the top exactly what produces the error or have you edited the code before posting it here. It might be hard to debug this issue because I cannot reproduce it. My guess is that something is special about your setup. Please see if you can narrow down when this happens and provide as much info as possible. How many workers do you have? Does it happen only when a single process? How many nodes? Any restriction on the file system access on those nodes?

**Comment by raminammour** [comment]
I could not reproduce it consistently either, it happens sporadically. However, it appears that our system is unstable today, and is being rebooted now. I am closing the issue suspecting that our system is the culprit here.

Thanks for the help, and sorry if I wasted your time :)
