### ISSUE TITLE
Incorrect results in substract operation -(A::Number, B::DArray)

### ISSUE THREAD

**Issue by JosmanPS** [JuliaParallel/DistributedArrays.jl#60]
When using operations like:

```julia
x = dones(10)
y = 10 - x
```

Values in `y` must be `9.0`, but it returns `-9.0`.

Similar issues happen when using other operators like `10 ./ x`.

**Comment by jiahao** [comment]
Thanks for finding an embarrassing error.

The problem is that we incorrectly define operations like `.-` and `./` [in this loop](https://github.com/JuliaParallel/DistributedArrays.jl/blob/6bef5d988c140976c584471ce66e52d797d7a956/src/DistributedArrays.jl#L818-L823) assuming that they are commutative, when they are obviously not.

We'd be happy to take a PR with the necessary fixes and tests if you might be willing to contribute some code changes.

**Comment by JosmanPS** [comment]
I'll work on that. Gonna send a pull request as soon as posible.

**Comment by JosmanPS** [comment]
@jiahao The pull request #61 is ready.
